enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-skypack.cjs
    spec: bundles/@yarnpkg/plugin-skypack.js

yarnPath: .yarn/releases/yarn-sources.cjs
