name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Commit bundle changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update bundles/@yarnpkg/plugin-skypack.js"
          file_pattern: bundles/@yarnpkg/plugin-skypack.js
